version: '3'
services:

  app:
    build: .
    ports:
      - "8443:8443"
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=students
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ric
    ports:
      - "5432:5432"
    restart: always